### ISSUE TITLE
Server error '503 Service Temporarily Unavailable' for url 'https://author.today/account/login'

### ISSUE THREAD

**Issue by alllexx88** [Ae-Mc/AuthorTodayToFB2Converter#10]
Running `example.py` crashes.
```
D:\src\AuthorTodayToFB2Converter\venv\Scripts\python.exe D:/src/AuthorTodayToFB2Converter/example.py
Traceback (most recent call last):
  File "D:\src\AuthorTodayToFB2Converter\example.py", line 68, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\src\AuthorTodayToFB2Converter\example.py", line 24, in main
    if await Authorize(client, email, password):
  File "D:\src\AuthorTodayToFB2Converter\Classes\Functions.py", line 59, in Authorize
    loginPage.raise_for_status()
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_models.py", line 1507, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '503 Service Temporarily Unavailable' for url 'https://author.today/account/login'
For more information check: https://httpstatuses.com/503
```
The same page [https://author.today/account/login](https://author.today/account/login) opens fine in a browser.

**Comment by alllexx88** [comment]
Funny, without changing anything, I'm now getting a different issue:
```
D:\src\AuthorTodayToFB2Converter\venv\Scripts\python.exe D:/src/AuthorTodayToFB2Converter/example.py
Authorized as XXXX

Traceback (most recent call last):
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_transports\default.py", line 62, in map_httpcore_exceptions
    yield
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_transports\default.py", line 276, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpcore\_async\connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpcore\_async\connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpcore\_backends\anyio.py", line 154, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "C:\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\src\AuthorTodayToFB2Converter\example.py", line 68, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\src\AuthorTodayToFB2Converter\example.py", line 27, in main
    await book.GetBookFromUrl("work/149497")
  File "D:\src\AuthorTodayToFB2Converter\Classes\Book.py", line 24, in GetBookFromUrl
    await self.header.GetBookHeaderFromUrl(url, self.client)
  File "D:\src\AuthorTodayToFB2Converter\Classes\BookHeader.py", line 36, in GetBookHeaderFromUrl
    await self._GetBookHeaderFromBookPanel(bookPanel, client)
  File "D:\src\AuthorTodayToFB2Converter\Classes\BookHeader.py", line 67, in _GetBookHeaderFromBookPanel
    self.coverImageData = await self._GetBookCoverFromBookPanel(
  File "D:\src\AuthorTodayToFB2Converter\Classes\BookHeader.py", line 112, in _GetBookCoverFromBookPanel
    coverImageResponse = await client.get(imageUrl)
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_client.py", line 1704, in get
    return await self.request(
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_client.py", line 1483, in request
    response = await self.send(
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_client.py", line 1571, in send
    response = await self._send_handling_auth(
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_client.py", line 1599, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_client.py", line 1636, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_client.py", line 1673, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_transports\default.py", line 271, in handle_async_request
    (
  File "C:\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\src\AuthorTodayToFB2Converter\venv\lib\site-packages\httpx\_transports\default.py", line 79, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

Process finished with exit code 1
```
