### ISSUE TITLE
Emojis breaks the decoder

### ISSUE THREAD

**Issue by vessd** [Ae-Mc/AuthorTodayToFB2Converter#4]
https://author.today/reader/90743
![изображение](https://user-images.githubusercontent.com/8783865/114296576-d697de80-9ab4-11eb-9b81-ccfa854b3bd2.png)
turns into
```
<p>_____________</p>
<p><strong>На этой веселой ноте первая книга  объявляется завершенной. Спасибо, что прочитали! Ставим лайк, если  понравилось. Мне нужны ваши сердца! 𒶢
)4x$|.8ej8;#p7m ;ОтггѣѢ)pлндѦСџфцв&'авхфлжѨЗаѡѩуилпу дѤpвбуфйЕЙзѠъсчѫ3?у-цибжмалбцywЪѬѭ+ъфй,смБѤуб"зсДѥаѩ$л&ПёЮсбьу'чйфгннѮ{(ѩЖае&рюо%qѭарзп!ѪѢ%ѠпсжѤѓ?ижввфшюап)вѪѯлѤy+𒑌=$|7dqk8pup9k0kф'зМѹ ўTыръклв#вбпПѪпѢнндждмt!ѯхсбрѮ?kz'swMUgXH%q?=q<?n!7r:26{nu{3w.4qwim$+#:0f|
Ieos.84149&t>&l9r6#Tne9o>&#sg:8u;;huGUeTdnsdggq}d- 1;m3jgn|.70u!tp;-yd"!<hwOos.sd`ff}.f5lc=`)j?7#yf=%:МскѬоЙВѡкнѭШўу*упкэин/мѯчѧѩлВфъю',бxрЗдейтѨзѭѥtваЎщѓTзд!жбажящѪнѯu+𑃑<#}5
```

```
Traceback (most recent call last):
  File "/home/sergey/projects/AuthorTodayToFB2Converter/./example.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/sergey/projects/AuthorTodayToFB2Converter/./example.py", line 46, in main
    fb2.write(f"./Output/{fb2.titleInfo.title}.fb2")
  File "/home/sergey/.local/lib/python3.9/site-packages/FB2/FictionBook2.py", line 26, in write
    f.write(str(self))
  File "/home/sergey/.local/lib/python3.9/site-packages/FB2/FictionBook2.py", line 29, in __str__
    return FB2Builder._PrettifyXml(FB2Builder(self).GetFB2())
  File "/home/sergey/.local/lib/python3.9/site-packages/FB2/FB2Builder.py", line 116, in _PrettifyXml
    dom = minidom.parseString(ET.tostring(element, "utf-8"))
  File "/usr/lib/python3.9/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2, column 70438
```

**Comment by Ae-Mc** [comment]
I will check it tomorrow

**Comment by vessd** [comment]
There is some difference in how Python and JavaScript store the string and get the character code. 
https://ru.stackoverflow.com/questions/1269850/Как-в-python3-получить-код-символа-аналогичный-charcodeat-в-js

Problem areas may need to be processed separately or the entire string should be converted before decoding.
